name: Build-Waveshare-RP2350B-Hybrid
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: micropython/micropython
          submodules: true

      - name: Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi build-essential python3 libnewlib-arm-none-eabi

      - name: mpy-cross
        run: make -C mpy-cross

      - name: Patch Pins
        run: |
          CONF="ports/rp2/boards/RPI_PICO2_W/mpconfigboard.h"
          
          # Loesche alle alten Definitionen, damit es keinen "Exit-Code 2" (Redefinition) gibt
          sed -i '/CYW43_PIN_WL/d' $CONF
          sed -i '/MICROPY_HW_PSRAM/d' $CONF
          
          # PSRAM auf Pin 47 (Waveshare & Pimoroni gleich)
          echo "#define MICROPY_HW_PSRAM_CS_PIN (47)" >> $CONF
          echo "#define MICROPY_HW_PSRAM_MAX_SEG_SIZE (8 * 1024 * 1024)" >> $CONF
          echo "#define MICROPY_HW_QMI_SUPPORT (1)" >> $CONF
          
          # WLAN Pins fuer Waveshare RP2350B-Plus-W
          echo "#define CYW43_PIN_WL_REG_ON (36)" >> $CONF
          echo "#define CYW43_PIN_WL_DATA (37)" >> $CONF
          echo "#define CYW43_PIN_WL_CS (38)" >> $CONF
          echo "#define CYW43_PIN_WL_CLK (39)" >> $CONF
          
          # WLAN auf PIO 1 zwingen (PIO 0 ist oft durch QMI/PSRAM belegt)
          echo "#define CYW43_PIO_INSTANCE 1" >> $CONF

      - name: Build
        run: |
          make -C ports/rp2 BOARD=RPI_PICO2_W BOARD_VARIANT=rp2350

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: waveshare-hybrid-firmware
          path: ports/rp2/build-RPI_PICO2_W/firmware.uf2
